from configs.master_config import CONFIG


class TestingConfig(object):
    BATCH_SIZE = CONFIG.TEST_BATCHSIZE
    HIGHRES_LOG_PATH = CONFIG.TEST_HIGHRESNET_MODEL_PATH
    BASELINE_REGRESSOR_LOG_PATH = CONFIG.TEST_BASELINE_REGRESSOR_MODEL_PATH